language: node_js
node_js: 10

install: ./install.sh
script: npm run build
after_success: package.sh

jobs:
  include:
    - os: linux
      python: 2.7
    - os: osx
      before_install: pyenv install 2.7.17 && pyenv global 2.7.17
    - os: windows
      before_install: choco install python2 visualstudio2019buildtools && npm install --global --production windows-build-tools
